
[app]
	port = 8000

[logger]
	prettyLogging = true # Only in development environment

[database]
	host		= "postgres_db"
	port		= 5432
	name		= "noteapp_golang"
	username	= "postgres"
	password	= "password"
